# --------------------------------------------------------------------
# 🚀 AUTOGENERATED FILE: DO NOT EDIT MANUALLY
# Generated by tools/generate_static_zones.py
# --------------------------------------------------------------------

output "zones" {
  description = "Map of available Vespa Cloud zones grouped by environment."
  value = {
    dev = {
      azure_eastus_az1 = {
        azure_region  = "eastus"
        environment   = "dev"
        name          = "dev.azure-eastus-az1"
        physical_zone = "eastus-az1"
        region        = "azure-eastus-az1"
        short_name    = "dev.eastus-az1"
        enclave_infra = local.enclave_infra
      }
    }
  }
}
