#!/usr/bin/env python3
"""
Generate a static outputs.tf file from the __all_zones variable in variables.tf.
No external dependencies required.
"""

import sys, json, re
from pathlib import Path


def extract_all_zones_block(text: str) -> str:
    lines = text.splitlines()
    start, depth, capture = None, 0, []
    for i, line in enumerate(lines):
        if re.search(r'variable\s+"__all_zones"', line):
            start = i
        if start is not None and "default" in line:
            # look for the first '[' after default =
            after_default = line.split("default", 1)[1]
            if "[" in after_default:
                depth = after_default.count("[") - after_default.count("]")
                capture.append(after_default.split("[", 1)[1])
            continue
        elif start is not None and depth > 0:
            depth += line.count("[") - line.count("]")
            capture.append(line)
            if depth == 0:
                break
    if not capture:
        sys.exit("❌ Could not find __all_zones default block.")
    block = "[" + "\n".join(capture)
    # ensure it ends properly
    block = re.sub(r"]\s*[,}]*\s*$", "]", block)
    return block

def parse_zones(block: str):
    # Minimal HCL→JSON transform
    block = re.sub(r'([a-zA-Z0-9_]+)\s*=', r'"\1":', block)
    block = block.replace("'", '"')

    # Remove trailing commas before closing braces/brackets
    # e.g., "{ ... , }" or "[ ... , ]"
    block = re.sub(r',(\s*[\]}])', r'\1', block)

    try:
        return json.loads(block)
    except Exception as e:
        sys.exit(f"❌ Failed to parse default block: {e}")

def build_output(zones):
    result = {}
    for z in zones:
        env, phys = z["environment"], z["physical_zone"]
        region = f"azure-{phys}"
        key = f"azure_{phys.replace('-', '_')}"
        result.setdefault(env, {})[key] = {
            "environment": env,
            "physical_zone": phys,
            "name": f"{env}.{region}",
            "short_name": f"{env}.{phys}",
            "region": region,
            "azure_region": phys.split("-")[0],
        }
    return result


def write_outputs(path: Path, data):
    with open(path, "w", encoding="utf-8") as f:
        env_keys = sorted(data.keys())
        f.write("# --------------------------------------------------------------------\n")
        f.write("# 🚀 AUTOGENERATED FILE: DO NOT EDIT MANUALLY\n")
        f.write("# Generated by tools/generate_static_zones.py\n")
        f.write("# --------------------------------------------------------------------\n\n")
        f.write('output "zones" {\n')
        f.write('  description = "Map of available Vespa Cloud zones grouped by environment."\n')
        f.write("  value = {\n")
        for env in env_keys:
            f.write(f"    {env} = {{\n")
            regions = data[env]
            for rkey in sorted(regions.keys()):
                info = regions[rkey]
                f.write(f"      {rkey} = {{\n")
                for k in sorted(info.keys()):
                    f.write(f'        {k} = "{info[k]}"\n')
                # Add enclave_infra as a dynamic reference
                f.write('        enclave_infra = local.enclave_infra\n')
                f.write("      }\n")
            f.write("    }\n")
        f.write("  }\n")
        f.write("}\n")
    print(f"✅ Generated {path}")


def main():
    if len(sys.argv) != 3:
        print("Usage: generate_static_zones.py <variables.tf> <outputs.tf>")
        sys.exit(1)

    src, dest = Path(sys.argv[1]), Path(sys.argv[2])
    text = src.read_text(encoding="utf-8")
    block = extract_all_zones_block(text)
    zones = parse_zones(block)
    data = build_output(zones)
    write_outputs(dest, data)


if __name__ == "__main__":
    main()
